language: python
python:
  - "2.7"
install: 
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip pandas nose'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - python setup.py install
script: 
  - "nosetests -w test/ -v"
